export const myProject = [
  {
    id: 1,
    name: "Vesto",
    category: "react",
    info: "An e-commerce website for a clothing store, allowing users to view products, select color and size, place orders, and contact the seller through social media. Built with React, Tailwind CSS, Node.js, Express, and MongoDB.",
    image: "projects/Vesto.webp",
    link: "https://vesto-fashion.vercel.app/",
    code: "https://github.com/DavidRN6/Vesto",
    allProjects: true,
  },
  {
    id: 2,
    name: "Technocrete Constructions",
    category: "react",
    info: "Created a responsive portfolio site for TechnoCrete using React.js, Tailwind CSS, and Framer Motion, featuring smooth animations, modern design, and project/service showcases to boost client engagement.",
    image: "projects/technocrete-constructions.webp",
    link: "https://technocrete-constructions.com/",
    code: "https://github.com/DavidRN6/Techno-Crete",
    allProjects: true,
  },
  {
    id: 3,
    name: "iLaw Chat Bot",
    category: "react",
    info: "an AI-powered legal chatbot built collaboratively with a team of law students, designed to assist with legal inquiries, explain legal concepts, and support research in Egyptian law. Focuses on simplifying legal information and legal issues.",
    image: "projects/iLaw.webp",
    link: "https://i-law.vercel.app/",
    code: "https://github.com/DavidRN6/iLaw",
    allProjects: true,
  },
  {
    id: 4,
    name: "Art Of Spirit",
    category: "react",
    info: "Built a full-stack eCommerce admin dashboard with React, Node.js, Express, and MongoDB, featuring order management, secure authentication, and Cloudinary-based product handling.",
    image: "projects/artofspirit.webp",
    link: "https://art-of-spirit.vercel.app/",
    code: "https://github.com/DavidRN6/Art-Of-Spirit",
    allProjects: true,
  },
  {
    id: 5,
    name: "Hagogah",
    category: "react",
    info: "Hagogah Restaurant’s website is a platform for the famous Hagogah restaurant, where customers can view the menu, order food, explore different dishes along with their prices, and access the restaurant’s social media pages",
    image: "projects/Hagogah.webp",
    link: "https://davidrn6.github.io/Hagogah/",
    code: "https://github.com/DavidRN6/Hagogah",
    allProjects: true,
  },
  {
    id: 6,
    name: "Shopsy",
    category: "react",
    info: "Developed a responsive clothing e-commerce web app using React.js, Tailwind CSS, and AOS, with dark mode, image sliders, Search Bar, scroll animations, and a clean UI built from reusable components.",
    image: "projects/Shopsy.webp",
    link: "https://davidrn6.github.io/Shopsy/",
    code: "https://github.com/DavidRN6/Shopsy",
    allProjects: true,
  },
  {
    id: 7,
    name: "My Travel Journal",
    category: "react",
    info: "Built a personal website with React.js featuring a clean, responsive design with soft colors and elegant UX. It includes a travel journal section with a map, allowing users to explore and share their travel experiences.",
    image: "projects/My Travel Journal.webp",
    link: "https://davidrn6.github.io/my-travel-journal/",
    code: "https://github.com/DavidRN6/my-travel-journal",
    allProjects: true,
  },
  {
    id: 8,
    name: "Portfolio (old)",
    category: "javascript",
    info: "Created an early personal portfolio with HTML, CSS, and JavaScript to showcase my skills and projects, featuring a simple, clean layout. It highlights my journey as a developer and serves as a foundation for my current portfolio.",
    image: "projects/Old-Portfolio.webp",
    link: "https://davidrn6.github.io/Portfolio/",
    code: "https://github.com/DavidRN6/Portfolio",
    allProjects: true,
  },
  {
    id: 9,
    name: "CRUDS",
    category: "javascript",
    info: "Developed a product management program to add products with price, taxes, discount, and quantity, automatically calculating totals for inventory and sales tracking. It features a user-friendly interface for managing product data.",
    image: "projects/CRUDS.webp",
    link: "https://davidrn6.github.io/CRUDS/",
    code: "https://github.com/DavidRN6/CRUDS",
    allProjects: true,
  },
  {
    id: 10,
    name: "Iphone",
    category: "javascript",
    info: "Built a dynamic website showcasing iPhone categories with color options, where selecting a color updates the site's design. Created with HTML, CSS, and JavaScript, emphasizing interactivity and responsiveness.",
    image: "projects/Iphone.webp",
    link: "https://davidrn6.github.io/Iphone-project/",
    code: "https://github.com/DavidRN6/Iphone-project",
    allProjects: true,
  },
  {
    id: 11,
    name: "XO Game",
    category: "javascript",
    info: "Created a dynamic iPhone website where selecting a color updates the entire site's design, offering an interactive experience. This project showcases my skills in creating responsive and engaging web applications.",
    image: "projects/XO Game.webp",
    link: "https://davidrn6.github.io/XO-Game/",
    code: "https://github.com/DavidRN6/XO-Game",
    allProjects: true,
  },
  {
    id: 12,
    name: "Silencer",
    category: "css",
    info: "A simple practice project using Bootstrap, featuring a clean, responsive design and hands-on experience with Bootstrap's grid and components. it boasts a modern layout with a focus on usability and aesthetics.",
    image: "projects/Silencer.webp",
    link: "https://davidrn6.github.io/bootstrap-project/",
    code: "https://github.com/DavidRN6/bootstrap-project",
    allProjects: true,
  },
  {
    id: 13,
    name: "Adidas",
    category: "css",
    info: "My first HTML & CSS project, featuring a simple layout to showcase my skills and projects, though non-responsive and basic. It serves as a foundation for my current portfolio, highlighting my journey as a developer.",
    image: "projects/adidas.webp",
    link: "https://davidrn6.github.io/Adidas/",
    code: "https://github.com/DavidRN6/Adidas",
    allProjects: true,
  },
];
