export const myProject = [
  {
    id: 1,
    name: "Art Of Spirit",
    category: "react",
    info: "Developed a full-stack eCommerce admin dashboard using React, Node.js, Express, and MongoDB. Enabled order management with real-time status updates, secure token-based authentication, and product/image handling via Cloudinary integration.",
    image: "projects/artofspirit.webp",
    link: "https://art-of-spirit.vercel.app/",
    code: "https://github.com/DavidRN6/Art-Of-Spirit",
    allProjects: true,
  },
  {
    id: 2,
    name: "Technocrete Constructions",
    category: "react",
    info: "Built a responsive portfolio website for TechnoCrete using React.js, Tailwind CSS, React Icons, React Slick, and Framer Motion. The site showcases projects and services with smooth scrolling, animated transitions, and a clean, modern layout to enhance client engagement.",
    image: "projects/technocrete-constructions.webp",
    link: "https://technocrete-constructions.com/",
    code: "https://github.com/DavidRN6/Techno-Crete",
    allProjects: true,
  },
  {
    id: 3,
    name: "Shopsy",
    category: "react",
    info: "Developed a responsive e-commerce web app for clothing using React.js, Tailwind CSS, and AOS. Features include dark mode support, image sliders (React Slick), scroll animations, and a clean UI built with reusable React components for seamless user experience.",
    image: "projects/Shopsy.webp",
    link: "https://davidrn6.github.io/Shopsy/",
    code: "https://github.com/DavidRN6/Shopsy",
    allProjects: true,
  },
  {
    id: 4,
    name: "My Travel Journal",
    category: "react",
    info: "A simple and visually calming personal website built with React.js. It features a clean layout, soft colors, and smooth responsiveness across devices. The design emphasizes elegance and clarity, making it a favorite project from a visual and UX perspective.",
    image: "projects/My Travel Journal.webp",
    link: "https://davidrn6.github.io/my-travel-journal/",
    code: "https://github.com/DavidRN6/my-travel-journal",
    allProjects: true,
  },
  {
    id: 5,
    name: "Portfolio (old)",
    category: "javascript",
    info: "A personal portfolio website built using HTML, CSS, and JavaScript. It showcases information about me, my skills, and the projects I’ve worked on. Designed with a simple and clean layout to reflect my early development journey.but it old now I use this portfolio",
    image: "projects/Old-Portfolio.webp",
    link: "https://davidrn6.github.io/Portfolio/",
    code: "https://github.com/DavidRN6/Portfolio",
    allProjects: true,
  },
  {
    id: 6,
    name: "CRUDS",
    category: "javascript",
    info: "A product management program that allows users to add products with details such as price, taxes, discount, and quantity. It automatically calculates the total price for each product. Useful for managing inventory, sales tracking, or small business operations.",
    image: "projects/CRUDS.webp",
    link: "https://davidrn6.github.io/CRUDS/",
    code: "https://github.com/DavidRN6/CRUDS",
    allProjects: true,
  },
  {
    id: 7,
    name: "Iphone",
    category: "javascript",
    info: "A dynamic website that displays iPhone categories with various color options. Upon selecting a specific color, the entire website design adapts to reflect the chosen color. Built using HTML, CSS, and JavaScript, the project focuses on interactivity and responsive design.",
    image: "projects/Iphone.webp",
    link: "https://davidrn6.github.io/Iphone-project/",
    code: "https://github.com/DavidRN6/Iphone-project",
    allProjects: true,
  },
  {
    id: 8,
    name: "XO Game",
    category: "javascript",
    info: "This project is a dynamic website displaying iPhone categories with different color options. When a user selects a specific color, the entire website design adjusts to match that color, creating a seamless and interactive experience. Built with HTML, CSS, and JavaScript.",
    image: "projects/XO Game.webp",
    link: "https://davidrn6.github.io/XO-Game/",
    code: "https://github.com/DavidRN6/XO-Game",
    allProjects: true,
  },
  {
    id: 9,
    name: "Silencer",
    category: "css",
    info: "This project was a simple practice exercise using Bootstrap. It features a clean, minimal design with a focus on responsive layout. The project helped me get hands-on experience with Bootstrap's grid and components. One of the first projects.",      
    image: "projects/Silencer.webp",
    link: "https://davidrn6.github.io/bootstrap-project/",
    code: "https://github.com/DavidRN6/bootstrap-project",
    allProjects: true,
  },
  {
    id: 10,
    name: "Adidas",
    category: "css",
    info: "The first project I made. This project was my first using only HTML and CSS, showcasing my basic web development skills. It features a simple layout with content about myself and my projects. However, it is not responsive and lacks modern features.",      
    image: "projects/adidas.webp",
    link: "https://davidrn6.github.io/Adidas/",
    code: "https://github.com/DavidRN6/Adidas",
    allProjects: true,
  },
];
